### ISSUE TITLE
[bug] Up/down in hp inputs starts from 0

### ISSUE THREAD

**Issue by merx3** [imoshekov/frosthaven-assistant#36]
Steps to reproduce:
- Start a New Game
- On a player character, on hp click up/down 

Result: HP goes to 1 or -1
Expected: Current HP value is increased by one

Note: same happens for movement and attack

**Comment by imoshekov** [comment]
![image](https://github.com/user-attachments/assets/423c80bc-0568-419f-ac3e-ad7b8887ff51)
